---
kind: Namespace
apiVersion: v1
metadata:
  name: traefik-test
  labels:
    name: traefik-test

---
apiVersion: v1
data:
  index.html: |
    Hallo, wereld!
kind: ConfigMap
metadata:
  name: index.html
  namespace: traefik-test

---
apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: traefik-test
spec:
  ports:
  - port: 80
  selector:
    app: nginx
  type: NodePort

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: traefik-test
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
        volumeMounts:
        - name: htmlcontent
          mountPath: "/usr/share/nginx/html/"
          readOnly: true
      volumes:
      - name: htmlcontent
        configMap:
          name: index.html
          items:
          - key: index.html
            path: index.html
