apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: nginx
  name: nginx3
spec:
  replicas: 3
  selector:
    matchLabels:
      run: nginx3
  template:
    metadata:
      labels:
        run: nginx3
    spec:
      containers:
      - name: nginx
        image: nginx:1.16
