apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: nginx
  name: nginx1
spec:
  replicas: 3
  selector:
    matchLabels:
      run: nginx1
  template:
    metadata:
      labels:
        run: nginx1
    spec:
      containers:
      - name: nginx
        image: nginx:1.16
---
apiVersion: v1
kind: Service
metadata:
  name: nginx1-service
  namespace: nginx1
  labels:
    app: nginx1
spec:
  type: NodePort
  selector:
    app: nginx1
  ports:
    - port: 80
      targetPort: 80

